project0:       aak759Project0.o
        gcc -g -o aak759Project0.o project0.o -o project0

aak759Project0.o:       aak759Project0.c Project0.h
        gcc -g -c aak759Project0.c

clean:
        rm -f project0
